# mkdocs.yml
# Configuración de MkDocs para el sitio de Apuntes Sistemas de Gestión Empresarial
site_name: Apuntes Sistemas de Gestión Empresarial
site_url: https://sergio-apuntes.github.io/sge/


theme:
  name: material
  language: es
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - navigation.top              # Muestra el botón para volver al principio
    - content.code.copy           # Botón de copiar en bloques de código

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  # los siguientes son para los bloques de código
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Tabs para códigos de dos lenguajes o más
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  


plugins:
  - search
  - glightbox


nav:
  - Presentación: 
    - index.md

  - 1 ERP:
    - 1_1_IntroduccionERP.md
    - 1_2_Sistemas_Informacion.md
    - 1_3_Sistemas_Clave.md
    - 1_4_ERP_CRM.md
    - 1_5_ERP_actuales.md
    - 1_6_ERP_Libres_Privativos.md
    - 1_7_CRM_Actuales.md
    - 1_8_Modelos_Servicio.md
    - 1_9_Terminología.md
  
  - 2 Python:
  #  - 2_python.md
    - 2_1_IntroduccionPython.md
  #  - 2_2_PrimerosPasosPython.md
    - 2_2_ControlFlujo.md
    - 2_3_EstructurasDatos.md
    - 2_4_FuncionesExcepciones.md
    - 2_5_ModulosPaquetes.md
    - 2_6_ProgramacionOrientadaObjetos.md

  - 3 Git:  
    - 3_1_Guia_Git_Github.md

  - 4 Docker:
    - 4_1_Guia_Docker.md

  - 5 Instalacion de Odoo: 
    - 5_1_InstalarOdoo.md
    - 5_2_InstalarDocker.md
    - 5_3_InstalarUbuntu.md
  - 6 Introducción a odoo:
    - 6_1_ArquitecturaOdoo.md
    - 6_2_PrimerModulo.md
  - 7 Desarrollo módulo ejemplo:
    - 7_1_EjemploCreacionModeloBasico.md
    - 7_2_EjemploCamposBasicos.md
    - 7_3_EjemploCamposComputados.md
    - 7_4_EjemploExcepcionesMensajes.md
    - 7_5_EjemploCamposComputadosRelacionales.md
    - 7_6_EjemploCamposValoresDefecto.md
    - 7_7_EjemploHerencias.md
    - 7_8_EjemploMejorandoVistas.md
    - 7_9_EjemploDatosDemo.md
  - 8 Desarrollo con odoo:
    - 8_1_Modulos.md
    - 8_2_Campos.md
    - 8_3_ArchivosDeDatos.md
    - 8_4_AccionesYMenu.md
    - 8_5_Vistas.md
    - 8_6_Controladores.md
    - 8_7_Herencia.md
    - 8_8_Security.md
    - 8_9_Miscelanea.md
    
    