name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Opcional, si usas este tema

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force